spring:
  application:
    name: service-gateway

server:
  port: 8082

eureka:
  instance:
    leaseRenewalIntervalInSeconds: 10
    prefer-ip-address: true
    status-page-url: http://localhost:${server.port}/swagger-ui.html
  client:
    registryFetchIntervalSeconds: 5
    serviceUrl:
      defaultZone: http://localhost:8000/eureka/

zuul:
  routes:
    service1:
      path: /service1/**
      serviceId: fresh-air-life-counter
    service2:
      path: /service2/**
      serviceId: device-open-status

  add-proxy-headers: true

ribbon:
  eager-load:
    enabled: true
  ReadTimeout: 6000
  ConnectTimeout: 6000


